- name: Sleep for a random duration (supports fractional minutes)
  hosts: localhost
  vars:
    sleep_min: 0.25    # Default minimum sleep time in minutes
    sleep_max: 0.5     # Default maximum sleep time in minutes
  tasks:
    - name: Debug initial input variables
      debug:
        msg:
          - "sleep_min: {{ sleep_min }} (type={{ sleep_min | type_debug }})"
          - "sleep_max: {{ sleep_max }} (type={{ sleep_max | type_debug }})"

    - name: Calculate and debug sleep time bounds (inline calculation)
      debug:
        msg:
          - "sleep_min_secs: {{ (sleep_min | float * 60) | int }} (type={{ ((sleep_min | float * 60) | int) | type_debug }})"
          - "sleep_max_secs: {{ (sleep_max | float * 60) | int }} (type={{ ((sleep_max | float * 60) | int) | type_debug }})"

    - name: Calculate random sleep time (ensure integer type)
      set_fact:
        sleep_duration: "{{ range((sleep_min | float * 60) | int, (sleep_max | float * 60) | int + 1) | random | int }}"

    - name: Debug selected sleep duration
      debug:
        msg: "Sleeping for {{ sleep_duration | int }} seconds ({{ (sleep_duration | int) // 60 }} minutes and {{ (sleep_duration | int) % 60 }} seconds)."

    - name: Sleep for the random duration
      command: sleep {{ sleep_duration | int }}
